version: 2.3.0

experiment:
  name: 57-seqv2-lax-finetune
  engine: DQN_SEQ
  root_dir: experiments
  dir: null # AUTOMATICALLY SET

env:
  train:
    data:
      cities:
        - austin
        - dallas
        - sf
        - vegas
        - dc
        - miami
        - london
      dir: data

    action_scheme:
      name: GraphDiscreteRetrace
      args:
        step_size: 10
        num_directions: 32

    reward_scheme:
      name: DistRewardV2
      args:
        movement_length: ${env.train.action_scheme.args.step_size}
        traversed_weight: 0.5
        revisit_penalty: 25
        divergence_penalty: 25
        max_distance: 55
        exponent: 1
        normalize: false
        max_visited_len_search: 40
        max_accepted_visited: 15
        min_viable_path_len: 30
        apply_road_width: false

    stopper:
      name: WindowAverage
      args:
        min_percent: 0.75
        window_length: 10
        gameover_multiplier: 1.5

    renderer: # list supported
      VideoRenderer9000:
        frame_size:
          - 1000
          - 1000
        gamma: ${policy.dqn.discount_factor}
        fps: 3
        skip_rate: 0.33
        max_frames: 50
      TopViewRenderer:
        scale: 0.25
        fps: 30
        skip_rate: 0.75
        min_steps_activate: 40
        max_frames: 100

    base:
      episode_window_size:
        - 512
        - 512
      observation_shape:
        - 384
        - 384
      starting_location: null
      observation_mode: rgb+movement+actions
      experiment_dir: ${experiment.dir}
      actions_obs_len: 15

    wrappers:
      UndoW:
        num_undo: 15
        hard_reset_rate: 0.1
      EpisodicEnvW:
        max_steps: 300
        max_episodes: 30
      AutoSaveW:
        mode: episode
        period: 100
      ObservationAugmentationW:
        mode: train
        output_shape:
          - 192
          - 192
      InputRepresentationW:
        mode: stacked

  test:
    data:
      cities:
        - kansas city
        - montreal
        - la
      dir: ${env.train.data.dir}

    action_scheme: ${env.train.action_scheme}
    reward_scheme: ${env.train.reward_scheme}

    stopper:
      name: WindowAverage
      args:
        min_percent: 0.69
        window_length: 15
        gameover_multiplier: ${env.train.stopper.args.gameover_multiplier}

    renderer: ${env.train.renderer}

    base:
      starting_location: null
      episode_window_size: ${env.train.base.episode_window_size}
      observation_shape: ${env.train.base.observation_shape}
      observation_mode: ${env.train.base.observation_mode}
      experiment_dir: ${experiment.dir}
      actions_obs_len: ${env.train.base.actions_obs_len}
    wrappers:
      EpisodicEnvW:
        max_steps: 5000
        max_episodes: 10
      AutoSaveW:
        mode: episode
        period: 3
        start: 9
      ObservationAugmentationW:
        mode: test
        output_shape: ${env.train.wrappers.ObservationAugmentationW.output_shape}
      InputRepresentationW: ${env.train.wrappers.InputRepresentationW}

collector:
  num_train_envs: 7
  num_test_envs: 3
  train_seed: 11
  test_seed: 111
  buffer_type: PERB
  buffer_size: 6000
  alpha: 0.7
  beta: 0.5

policy:
  device: dp
  arch:
    actions_output_dim: 32
    actions_seq_len: ${env.train.base.actions_obs_len}
    hidden_sizes:
      - 128
      - 128
      - 128
    backbone:
      finetune: 1 # same as the LR decay milestone
      lr: 5e-4
      name: core.policy.networks.TIMM_ZOO
      args:
        name: tf_efficientnetv2_b0
        feature_vector_size: 256
        obs_channels: 4
        pretrained: true
  optimizer:
    name: torch.optim.AdamW
    args:
      lr: 1e-3
      weight_decay: 1e-4
      eps: 1e-8
  dqn:
    discount_factor: 0.75
    estimation_step: 3
    target_update_freq: 0
    reward_normalization: false
  checkpoint:
    filepath: null
    strict: true
    load_optimizer: true

trainer:
  args:
    max_epoch: 500
    step_per_epoch: 10000
    update_per_step: 0.2
    batch_size: 128
    step_per_collect: 154
    episode_per_test: 12
  train:
    eps: 0.25
    sched:
      - 10
      - 200
  test:
    eps: 0.01
  lr_scheduler:
    name: torch.optim.lr_scheduler.MultiStepLR
    args:
      milestones:
        - 1
        - 50
        - 100
      gamma: 0.5
      verbose: true
  checkpointer:
    monitor: rew_avg
    filename: policy_{epoch}_{rew_avg:.2f}
    save_last: true
    save_top_k: 3
    mode: max
    verbose: true
  experiment_dir: ${experiment.dir}
  reward_threshold: 1000
