version: 2.2.0

experiment:
  name: 42-rqdn-unnormal
  engine: RDQN
  root_dir: experiments
  dir: null # AUTOMATICALLY SET

env:
  train:
    data:
      cities:
        - toronto
        - paris
        - la
        - chicago
        - houston
      dir: data

    action_scheme:
      name: GraphDiscreteRetrace
      args:
        step_size: 10
        num_directions: 32

    reward_scheme:
      name: DistReward
      args:
        neutral_distance: 5
        revisit_distance: 20
        max_distance: 40
        exponent: 1
        normalize: false
        nearest_unvisited_len_thresh: 40 
        min_viable_path_len: 20
        apply_road_width: false

    stopper:
      name: WindowAverage
      args:
        min_average: -12
        window_length: 8
        gameover_multiplier: 1.5

    renderer: # list supported
      VideoRenderer9000:
        frame_size:
          - 1000
          - 1000
        gamma: ${policy.dqn.discount_factor}
        fps: 4
        max_frames: 150
      TopViewRenderer:
        scale: 0.25
        fps: 30
        skip_rate: 0.75
        min_steps_activate: 40
        max_frames: 100

    base:
      observation_shape:
        - 512
        - 512
      starting_location: null
      observation_mode: rgb+movement+road-mask
      experiment_dir: ${experiment.dir}

    wrappers:
      UndoW:
        num_undo: 20
        hard_reset_rate: 0.1
      EpisodicEnvW:
        max_steps: 300
        max_episodes: 50
      AutoSaveW:
        mode: episode
        period: 150
      ObservationAugmentationW:
        mode: train
        output_shape:
          - 256
          - 256
        mask_shape:
          - 256
          - 256
      InputRepresentationW:
        mode: stacked

  test:
    data:
      cities:
        - kansas city
        - montreal
      dir: ${env.train.data.dir}

    action_scheme: ${env.train.action_scheme}
    reward_scheme: ${env.train.reward_scheme}

    stopper:
      name: WindowAverage
      args:
        min_average: -15
        window_length: 12
        gameover_multiplier: ${env.train.stopper.args.gameover_multiplier}

    renderer: ${env.train.renderer}

    base:
      starting_location: null
      observation_shape: ${env.train.base.observation_shape}
      observation_mode: ${env.train.base.observation_mode}
      experiment_dir: ${experiment.dir}
    wrappers:
      EpisodicEnvW:
        max_steps: 5000
        max_episodes: 10
      AutoSaveW:
        mode: episode
        period: 3
        start: 6
      ObservationAugmentationW:
        mode: test
        output_shape: ${env.train.wrappers.ObservationAugmentationW.output_shape}
        mask_shape: ${env.train.wrappers.ObservationAugmentationW.mask_shape}
      InputRepresentationW: ${env.train.wrappers.InputRepresentationW}

collector:
  num_train_envs: 5
  num_test_envs: 2
  train_seed: 11
  test_seed: 111
  buffer_type: PERB
  buffer_size: 3000
  alpha: 0.8
  beta: 0.5

policy:
  device: dp
  arch:
    backbone:
      name: core.policy.networks.LiteHRNetEx
      args:
        name: litehrnet18
        obs_channels: 4
        # pretrained: checkpoints/litehrnet_18_coco_384x288.pth
    mlp_input_dim: 128
    hidden_sizes:
      - 64
  optimizer:
    lr: 5e-4
    weight_decay: 1e-4 
  segmentation_criterion:
    num_classes: 2
    alpha: 0.1   
  dqn:
    loss_weights:
      - 10
      - 0.1
      - 0.05
    log_interval: 100
    discount_factor: 0.5
    estimation_step: 3
    target_update_freq: 5
  checkpoint: checkpoints/litehrnet_exp_32.ckpt

trainer:
  args:
    max_epoch: 500
    step_per_epoch: 10000
    update_per_step: 0.2
    batch_size: 92
    step_per_collect: 200
    episode_per_test: 15
  train:
    eps: 0.25
    sched:
      - 100
      - 400
  test:
    eps: 0.01
  checkpointer:
    monitor: rew_avg
    filename: policy_{epoch}_{rew_avg:.2f}
    save_last: true
    save_top_k: 3
    mode: max
    verbose: true
  experiment_dir: ${experiment.dir}
  reward_threshold: 1000
