---
version: 1
formatters:
  standard:
    format: '%(asctime)s %(levelname)s: %(message)s'
    datefmt: '%y-%b-%d %H:%M:%S'
  extended:
    format: '%(asctime)s %(process)d-%(levelname)s: %(message)s'
    datefmt: '%y-%b-%d %H:%M:%S'
  error:
    format: '%(asctime)s %(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s'
    datefmt: '%y-%b-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard

  debug_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: {logdir}/debug.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8

  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: {logdir}/info.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8

  warn_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: WARN
    formatter: standard
    filename: {logdir}/warn.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8

  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: standard
    filename: {logdir}/errors.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8

  critical_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: CRITICAL
    formatter: error
    filename: {logdir}/critical.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8

loggers:
  dev:
    leve: DEBUG
    handlers:
      - console
      - debug_file_handler
      - info_file_handler
      - warn_file_handler
      - error_file_handler
    propagate: false

  test:
    level: WARN
    handlers:
      - warn_file_handler
    propagate: false

root:
  level: DEBUG
  handlers:
    - debug_file_handler