version: 2.0.0

experiment:
  name: 7-dqn-new
  root_dir: experiments
  dir: null # AUTOMATICALLY BE CALCULATED

data:
  city: toronto
  data_dir: data

env:
  train:
    action_scheme:
      name: MaskDiscrete
      args:
        step_size: 10
        num_directions: 32
        brush_width: 2
    reward_scheme:
      name: MaskReward
      args:
        revisit_weight: 1
        error_weight: 2
    stopper:
      name: MaxPenaltyLatest
      args:
        max_negative: -10
        window: 7
    base:
      renderer: null
      observation_shape:
        - 256
        - 256
      starting_location: null
      observation_mode: stacked
      experiment_dir: ${experiment.dir}
    wrappers:
      EpisodicEnvW:
        max_steps: 200
        max_episodes: 1
      AutoRenderW:
        mode: step
      AutoSaveW:
        mode: episode
        period: 500
      PreprocessObservationW: []

  test:
    action_scheme: ${env.train.action_scheme}
    reward_scheme: ${env.train.reward_scheme}
    stopper:
      name: MaxPenaltyLatest
      args:
        max_negative: -20
        window: 15
    base:
      auto_render: step
      auto_save: episode
      renderer: video
      starting_location: null
      observation_shape: ${env.train.base.observation_shape}
      observation_mode: ${env.train.base.observation_mode}
      experiment_dir: ${experiment.dir}
    wrappers:
      EpisodicEnvW:
        max_steps: 250
        max_episodes: 5
      AutoRenderW:
        mode: step
      AutoSaveW:
        mode: episode
      PreprocessObservationW: ${env.train.wrappers.PreprocessObservationW}

collector:
  num_train_envs: 8
  num_test_envs: 2
  train_seed: 11
  test_seed: 111
  buffer_type: PERB
  buffer_size: 4096
  alpha: 0.9
  beta: 0.5

policy:
  device: dp
  backbone:
    name: core.policy.networks.EfficientNetEx
    args:
      name: efficientnet-b0
      feature_vector_size: 1000
      obs_channels: 4
      pretrained: True
  optimizer:
    lr: 1e-3
    weight_decay: 1e-3
  dqn:
    discount_factor: 0.75
    estimation_step: 4
    target_update_freq: 20
    reward_normalization: false
  checkpoint: experiments/5-dqn-efficientnet-b0/version_0/checkpoints/latest_policy.pth

trainer:
  args:
    max_epoch: 500
    step_per_epoch: 10000
    update_per_step: 0.04
    batch_size: 256
    step_per_collect: 100
    episode_per_test: 6
  train:
    eps: 0.4
    sched:
      - 100
      - 400
  test:
    eps: 0.05
  experiment_dir: ${experiment.dir}
  reward_threshold: 1000
